<div class="footer">
    <!--lien vers des CGU fictives pour le moment-->
    <div class="CGU">
        <a href="https://gearsofwar.fandom.com/fr/wiki/Coalition_des_Gouvernements_Unis">CGU</a>
    </div>
    <!--lien de contact fictif pour le moment-->
    <div class="contact">
        <a href = "https://www.youtube.com/watch?v=YUNtPBmQTR8">contact</a>
    </div>
    <!--redesign footer to make it serious and stop trolling moron-->
</div>