<!--layout principale , il est afficher sur chaque page du site-->

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="https://seeklogo.com/images/X/Xbox_360_Gears_Of_War-logo-CC2C2C77F4-seeklogo.com.png">
    <link rel="stylesheet" type="text/css" href="https://thomascavelier.sites.3wa.io/GEARS_FINAL/public/CSS/style.css">
    <title>Gears mini painting guide</title>
</head>
<body>

    <?php
if (isset($_SESSION["user"])){
    // header
    require 'src/vues/navbar.phtml';

    // main
    if (isset($layout)) {
        require $layout.'.phtml';
    }

    // footer
    require 'src/vues/footer.phtml';

    }else{
        if(isset($layout)){
            require 'src/vues/log-form.phtml';
            require 'src/vues/sign-up.phtml';
        }
    }


    //think to redo your if isset session and hide what's need to be

    ?>



</body>
</html>
