<!--formulaire de connexion au site-->
<form method="post" action="https://thomascavelier.sites.3wa.io/GEARS_FINAL/login">
    <!--champ permettant la connexion via le pseudo OU l'adresse mail, requis et ne peut etre vide-->
    <input type="text" name="username" value="" required="required" placeholder="E-mail or username" />
    <!--champ de mot de passe , les caracteres sont cachés ne peut etre vide-->
    <input type="password" name="pwd" value="" required="required" placeholder="password" />
    <!--champ d'envoi du formulaire sous forme de bouton-->
    <input type="submit" name="submit" value="LOGIN" />
<!--fin de formulaire-->
</form>
