<!--navbar pour une navigation plus rapide sur le site-->

<nav>
    <ul>
        <li>you are logged as <?= $_SESSION['user']["username"]; ?> , welcome</li>
        <li><a href="https://thomascavelier.sites.3wa.io/GEARS_FINAL/index">HOME</a></li>
        <li><a href = "https://thomascavelier.sites.3wa.io/GEARS_FINAL/addfig">Add your mini</a></li>
        <li><form method="post" action="https://thomascavelier.sites.3wa.io/GEARS_FINAL/logout">
        <input type="submit" name="submit" value="LOGOUT" />
            </form></li>
    </ul>
</nav>

