<!--barre de recherche pour les minis-->
<label for="search" class="search">Search mini : </label>
    <!--pas besoin de bouton pour valider la recherche , le resultat s'affiche en direct-->
    <input type="text" id="search">
    <!--BR CAN GO AFTERWARDS , MAKE CLEAN SECTION , CLEAN DIV ETC -->
    <br>

 pick a mini and see what you need to paint it :
 <!--mise dans une section cible pour la requete AJAX , seule cette partie s'actualise -->
 <section id="listOfFigs">
<!--affichage de la liste des mini -->
<ul>
    <!--pour chaque figurine en tant qu'unité -->
    <?php foreach($args['figs'] as $fig): ?>
    <!--liste de liens menant vers la figurine specifique-->
    <li class="fig-list">
        <!--affichage de l'image cliquable -->
        <a href="display/<?= $fig->ID ?>" ><img src="public/uploads/<?= htmlspecialchars( $fig->picture) ?>" alt= "picture" class="picture-list"/></a>
        <!--le champ du nom est protegé-->
        <a href="display/<?= $fig->ID ?>" class="namelink" ><?= htmlspecialchars($fig->name) ?></a>

    </li>
    <?php endforeach ?>
</ul>
<!--fin de section -->
</section>