<?php

    //disposition de l'affichage des minis
    //pour chaque figurine en tant qu'unité ( ciblé par l'id pour ce cas)
    foreach($args['Fig'] as $figs): ?>
    <!--on crée une divste contenant ce que l'on veut afficher-->
        <section  class="display-cards">
            <div class="display-list">
                <!--ici le nom , proteger contre d'eventuels script placé lors de la création-->
                <div class="name"><?= htmlspecialchars($figs->name) ?></div>
                <!--ici l'image avec son dossier parent et la aussi protegé contre les script potentiellement mis dans le nom -->
                <div> <img src="../public/uploads/<?= htmlspecialchars( $figs->picture) ?>" alt= "picture" class="picture-display"/></div>
                <!--ici le fluff encore une fois protegé contre les scripts potentiels-->
                <div class="content"><?= htmlspecialchars($figs->content) ?></div>
            </div>
        </section>
    <?php endforeach ?>


<?php
    //disposition de l'affichage des peintures divées a la figurine
    //on recupere peintures divée a la mini
    $paints = Fig::getFigPaints($figs->ID);
    //pour chaque peinture en tant qu'unité ( ici ciblée par l'id)
    foreach($paints as $paint) {
        ?>

           <div class="paintAlign">
               <div  class="displayPaint" >
                   <!--affichage du nom et image des peintures-->
                   <!--les images des peintures sont au format blob dans la db-->
                   <!--meme si on ne peut creer de nouvelles peintures et au'elles sont en dur dans la db on protege le nom des peintures-->
                    <div class="paint" ><div class="ColorPicture"><?= $paint->color_picture ?></div> <div class="ColorName"><?= htmlspecialchars($paint->color_name) ?></div></div>
               </div>
           </div>

        <?php
    }
    ?>
<div class="upBack">
    <!--lien de renvoi vers la page principale du site-->
    <a href='https://thomascavelier.sites.3wa.io/GEARS_FINAL/index' class="backBut">Back to selection</a>

</div>

