<form action = "https://thomascavelier.sites.3wa.io/GEARS_FINAL/signup" method ="post">
    <input type="text" name="username" placeholder="username">
    <input type="password" name="pwd" placeholder="password">
    <input type="password" name="pwdRepeat" placeholder="repeat password">
    <input type="text" name="email" placeholder="E-mail">
    <button type="submit" name="submit"> SIGN UP  </button>
</form>
<p> /!\ le formulaire ne prends en compte que les caracteres "normaux" et les chiffres de 0 a 9<br>
/!\ce formulaire n'est visible que sur activation du sysadmin et n'est pas destiné a rester afficher sur cette page<br>
/!\il n'est la qu'a but de tester les failles de securité , d'ailleurs ce texte est voué a disparaitre aussi </p>