<form action = "https://thomascavelier.sites.3wa.io/GEARS_FINAL/signup" method ="post">
    <input type="text" name="username" placeholder="username">
    <input type="password" name="pwd" placeholder="password">
    <input type="password" name="pwdRepeat" placeholder="repeat password">
    <input type="text" name="email" placeholder="E-mail">
    <button type="submit" name="submit"> SIGN UP  </button>
</form>